pdp/member/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^voir/(?P<user_name>.+)$', views.details),
    url(r'^profil/editer$', views.edit_profile),

    url(r'^publications$', views.publications),
    url(r'^actions$', views.actions),

    url(r'^parametres/profil$', views.settings_profile),
    url(r'^parametres/compte$', views.settings_account),

    url(r'^connexion$', views.login_view),
    url(r'^inscription$', views.register_view),
    url(r'^deconnexion/$', views.logout_view),
    url(r'^$', views.index),
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    model = User

class GroupViewSet(viewsets.ModelViewSet):
    model = Group

# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns('',
    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
            template='search/search.html',
            form_class=ModelSearchForm),
        name='haystack_search'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SERVE:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/member/models.py
# coding: utf-8

from hashlib import md5

from django.db import models
from django.contrib.auth.models import User

from pdp.forum.models import Post, Topic
from pdp.tutorial.models import Tutorial
from pdp.article.models import Article


class Profile(models.Model):

    """Represents an user profile."""

    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    user = models.ForeignKey(User, unique=True, verbose_name=u'Utilisateur')

    site = models.CharField(u'Site internet', max_length=128, blank=True)
    show_email = models.BooleanField(u'Afficher adresse mail publiquement',
                                     default=True)

    avatar_url = models.CharField(
        u'URL de l\'avatar', max_length=128, null=True, blank=True
    )

    biography = models.TextField(u'Biographie', blank=True)

    def __unicode__(self):
        """Textual representation of a profile."""
        return self.user.username

    def get_absolute_url(self):
        """Absolute URL to visualize this profile."""
        # TODO: use reverse
        return u'/membres/voir/{0}'.format(self.user.username)

    def get_avatar_url(self):
        """Get the member's avatar URL (using custom URL or Gravatar)."""
        if self.avatar_url:
            return self.avatar_url
        else:
            return 'https://secure.gravatar.com/avatar/{0}?d=identicon'\
                .format(md5(self.user.email).hexdigest())

    def get_post_count(self):
        """Total number of answers of the member on the forums."""
        return Post.objects.all().filter(author__pk=self.user.pk).count()

    def get_topic_count(self):
        """Total number of topics created on the forums by the member."""
        return Topic.objects.all().filter(author=self.user).count()

    def get_followed_topics(self):
        """Get all the topics the user is currently following."""
        return Topic.objects.filter(topicfollowed__user=self.user)\
            .order_by('-last_message__pubdate')

    # Tutorial

    def get_tutorials(self):
        """GGet all the tutorials written or being written by this member."""
        return Tutorial.objects.filter(authors=self.user.pk)

    def get_visible_tutorials(self):
        """Get all the tutorials published by this member."""
        return self.get_tutorials().filter(is_visible=True)

    def get_hidden_tutorials(self):
        """Get all the tutorials the member is currently writing."""
        return self.get_tutorials().filter(is_visible=False)

    # Article

    def get_articles(self):
        """Get all the articles written or being written by this member."""
        return Article.objects.all().filter(author=self.user)

    def get_visible_articles(self):
        """Get all the articles published by this member."""
        return self.get_articles().filter(is_visible=True)

    def get_hidden_articles(self):
        """Get all the articles the member is currently writing."""
        return self.get_articles().filter(is_visible=False)

pdp/member/forms.py
# coding: utf-8

from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Div, Fieldset, Submit, Field, HTML

from captcha.fields import CaptchaField

from pdp.member.models import Profile


class LoginForm(forms.Form):

    """Form used for login in users."""

    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)


class RegisterForm(forms.Form):

    """Form used for to register new users."""

    email = forms.EmailField(label='Adresse email')
    username = forms.CharField(label='Nom d\'utilisateur', max_length=30)
    password = forms.CharField(
        label='Mot de passe', max_length=76, widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label='Confirmation', max_length=76, widget=forms.PasswordInput
    )
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Fieldset(
                u'Identifiants',
                Field('username'),
                Field('password'),
                Field('password_confirm'),
                Field('email'),
            ),
            Fieldset(
                u'Captcha',
                Field('captcha'),
            ),
            Div(
                Submit('submit', 'Valider mon inscription'),
                HTML('<a href="/" class="button secondary">Annuler</a>'),
                css_class='button-group'
            )
        )
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        # Check that the password and it's confirmation match
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if not password_confirm == password:
            msg = u'Les mots de passe sont différents'
            self._errors['password'] = self.error_class([''])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password' in cleaned_data:
                del cleaned_data['password']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        # Check that the user doesn't exist yet
        username = cleaned_data.get('username')
        if User.objects.filter(username=username).count() > 0:
            msg = u'Ce nom d\'utilisateur est déjà utilisé'
            self._errors['username'] = self.error_class([msg])

        return cleaned_data


# update extra information about user
class ProfileForm(forms.Form):
    biography = forms.CharField(
        label='Biographie',
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder': 'Votre biographie au format Markdown.'}))
    site = forms.CharField(
        label='Site internet',
        required=False,
        max_length=128,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers votre site internet personnel '
                   '(ne pas oublier le http:// ou https:// devant).'}))
    show_email = forms.BooleanField(
        label='Afficher mon adresse mail publiquement',
        required=False)
    avatar_url = forms.CharField(
        label='Avatar',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers un avatar externe '
                   '(laisser vide pour utiliser Gravatar).'}))

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user
        profile = Profile.objects.get(user=self.user)

        # to get initial value form checkbox show email
        initial = kwargs.get('initial', {})
        value_checked = ''
        if 'show_email' in initial and initial['show_email']:
            value_checked = 'checked'

        self.helper.layout = Layout(
            Fieldset(
                u'Public',
                Field('biography'),
                Field('site'),
                Field('avatar_url'),
                # inline checkbox is not supported by crispy form
                HTML('<div id="div_id_show_email" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_show_email" > <input id="id_show_email" type="checkbox" class="checkboxinput" name="show_email" ' + value_checked + '/>\
                Afficher mon adresse mail publiquement</label></div>'),
            ),
            Div(
                Submit('submit', 'Editer mon profil'),
                css_class='button-group'
            )
        )
        super(ProfileForm, self).__init__(*args, **kwargs)


# to update a password

class ChangePasswordForm(forms.Form):
    password_new = forms.CharField(
        label='Nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)
    password_old = forms.CharField(
        label='Mot de passe actuel ', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(
        label='Confirmer le nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user

        self.helper.layout = Layout(
            Fieldset(
                u'Mot de passe',
                Field('password_old'),
                Field('password_new'),
                Field('password_confirm'),
            ),
            Div(
                Submit('submit', 'Changer mon mot de passe'),
                css_class='button-group'
            )
        )
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        password_old = cleaned_data.get('password_old')
        password_new = cleaned_data.get('password_new')
        password_confirm = cleaned_data.get('password_confirm')

        # Check if the actual password is not empty
        if password_old:
            user_exist = authenticate(
                username=self.user.username, password=password_old
            )
            if not user_exist and password_old != "":
                self._errors['password_old'] = self.error_class(
                    [u'Mot de passe incorrect.'])
                if 'password_old' in cleaned_data:
                    del cleaned_data['password_old']

        # Check that the password and it's confirmation match
        if not password_confirm == password_new:
            msg = u'Les mots de passe sont différents.'
            self._errors['password_new'] = self.error_class([msg])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password_new' in cleaned_data:
                del cleaned_data['password_new']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        return cleaned_data

templates/member/actions.html
{% extends "member/base.html" %}

{% block title %}
    Quoi de neuf ?
{% endblock %}

{% block headline %}
    Quoi de neuf ?
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Quoi de neuf ?</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <h2>Actions</h2>
        <ul>
            <li>
                <a href="{% url "pdp.member.views.details" user.username %}">
                    Voir votre profil
                </a>
            </li>
            <li>
                <a href="{% url "pdp.member.views.publications" %}">
                    Voir vos publications
                </a>
            </li>
            <li>
                <a href="{% url "pdp.member.views.settings_profile" %}">
                    Paramètres de votre profil
                </a>
            </li>
            <li>
                <a href="{% url "pdp.member.views.settings_account" %}">
                    Paramètres de votre compte
                </a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

templates/member/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Membres
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.member.views.index" %}">Membres</a></li>
{% endblock %}

templates/member/edit_profile.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
    Éditer mon profil
{% endblock %}

{% block headline %}
    Éditer mon profil
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
    <li class="current"><a href="#">Éditer mon profil</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST">
            <fieldset>
                <legend>Public</legend>
        
                <div class="control-group">
                    <label for="id_biography" class="control-label">Biographie</label>
                    <div class="controls">
                        <textarea name="biography" class="input-block-level" rows="10" id="id_biography"
                            placeholder="Votre biographie au format Markdown.">{{ profile.biography }}</textarea>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_site" class="control-label">Site internet</label>
                    <div class="controls">
                        <input type="text" name="site" id="id_site" class="input-block-level"
                        placeholder="Lien vers votre site internet personnel." value="{{ profile.site }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_email" class="control-label">Adresse mail</label>
                    <div class="controls">
                        <input type="text" name="email" id="id_email" class="input-block-level"
                        placeholder="Veuillez entrer une adresse email valide" value="{{ profile.user.email }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox">
                            <input type="checkbox" name="show_email"
                            {% if profile.show_email %}checked{% endif %}>
                            Afficher mon adresse mail publiquement
                        </label>
                    </div>
                </div>
        
            </fieldset>
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-pencil icon-white"></i>
                    Éditer
                </button>
        
                <a href="{{ profile.user.get_absolute_url }}" class="button secondary">
                    Annuler
                </a>
            </div>
        
            {% csrf_token %}
        
        </form>
    </div>
</div>



{% endblock %}

templates/member/index.html
{% extends "member/base.html" %}

{% block title %}
    Membres
{% endblock %}

{% block headline %}
    Membres
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Sur cette page vous pourrez trouver la liste des membres inscrits au site (actuellement {{ members.count }} membres).
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <p>
            {% for member in members %}
                {% include "member/member_item_common.part.html" %}
            {% endfor %}
        </p>
    </div>
</div>

{% endblock %}

templates/member/login.html
{% extends "member/base.html" %}

{% block title %}
    Connexion
{% endblock %}

{% block headline %}
    Se connecter
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Connexion</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
            <div class="alert-box warning">
                {{ error }}.
            </div>
            {% endif %}

            <p>
                Si vous n'avez pas de compte, vous pouvez <a href="{% url "pdp.member.views.register_view" %}" >vous inscrire</a>.
            </p>
        {% else %}
            <p>
                Vous êtes déjà connecté.
            </p>
        {% endif %}
    </div>
</div>

{% if not user.is_authenticated %}
<div class="row">
    <div class="large-7 large-offset-1 columns">
        <form method="post" action="{% url "pdp.member.views.login_view" %}">
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_username">Identifiant</label>
                </div>
                <div class="small-8 columns">
                    <input type="text" name="username" id="id_username" maxlength="30" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_password">Mot magique</label>
                </div>
                <div class="small-8 columns">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns"></div>
                <div class="small-8 columns">
                    <label>
                        <input type="checkbox" name="remember">
                        Connexion automatique
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="small-8 small-offset-4 columns">
                    <button type="submit" class="button">
                        Se connecter
                    </button>
                    <a href="/" class="button secondary">
                        Annuler
                    </a>
                </div>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

templates/member/member_item_common.part.html
{% load profile %}

{% with profile=member|profile %}
<a href="{{ member.get_absolute_url }}" class="member-item">
    <img src="{{ profile.get_avatar_url }}" width="16" height="16" alt="Avatar" />
    {{ member.username }}
</a>
{% endwith %}

templates/member/profile.html
{% extends "member/base.html" %}
{% load emarkdown %}
{% load markup %}
{% load humane_date %}
{% load email_obfuscator %}

{% block title %}
    {{ usr.username }}
{% endblock %}

{% block headline %}
    {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">{{ usr.username }}</a></li>
{% endblock %}

{% block headline-actions %}
    {% if user.is_authenticated %}
        {% ifequal profile.user user %}
            <a href="{% url "pdp.member.views.settings_profile" %}" class="button">
                <i class="icon-cog"></i>
                Paramètres
            </a>
        {% else %}
            <a class="button secondary" href="{% url "pdp.messages.views.new"%}?destinataire={{ usr.id }}">
                Envoyer un message
            </a>
        {% endifequal %}
    {% endif %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-2 columns">
        <p>
            <img src="{{ profile.get_avatar_url }}" alt="Avatar" width="80" height="80" class="th"/>
        </p>
    </div>
    <div class="large-10 columns">
        <p>
            {% if profile.show_email and user.is_authenticated %}
                Adresse mail : {{ usr.email|obfuscate_mailto }}<br />
            {% endif %}

            {% if profile.site %}
                Site internet : <a href="{{ profile.site }}">{{ profile.site }}</a><br />
            {% endif %}

            Inscrit {{ usr.date_joined|humane_date }},
            dernière connexion {{ usr.last_login|humane_date }}.
        </p>
    </div>
</div>

<div class="row">
    <div class="large-4 columns">
        <h3>Articles</h3>
        <table>
            <tbody>
                <tr>
                    <td>En cours de rédaction</td>
                    <td>{{ profile.get_hidden_articles.count }}</td>
                </tr>
                <tr>
                    <td>En ligne</td>
                    <td><a href="{% url "pdp.article.views.find_article" usr.username %}">{{ profile.get_visible_articles.count }}</a></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td>{{ profile.get_articles.count }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="large-4 columns">
        <h3>Tutoriels</h3>
        <table>
            <tbody>
                <tr>
                    <td>En cours de rédaction</td>
                    <td>{{ profile.get_hidden_tutorials.count }}</td>
                </tr>
                <tr>
                    <td>En ligne</td>
                    <td><a href="{% url "pdp.tutorial.views.find_tutorial" usr.username %}">{{ profile.get_visible_tutorials.count }}</a></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td>{{ profile.get_tutorials.count }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="large-4 columns">
        <h3>Forums</h3>
        <table>
            <tbody>
                <tr>
                    <td>Sujets créés</td>
                    <td><a href="{% url "pdp.forum.views.find_topic" usr.username %}">{{ profile.get_topic_count }}</a></td>
                </tr>
                <tr>
                    <td>Messages postés</td>
                    <td><a href="{% url "pdp.forum.views.find_post" usr.username %}">{{ profile.get_post_count }}</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{# Biography #}

{% if profile.biography %}

<div class="row">
    <div class="large-12 columns">
        <h2>Biographie</h2>
        {{ profile.biography|emarkdown }}
    </div>
</div>

{% endif %}

{% endblock %}

templates/member/publications.html
{% extends "member/base.html" %}

{% block title %}
    Publications
{% endblock %}

{% block headline %}
    Publications
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Publications</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <h3>Articles</h3>
        </div>
    </div>
    {% if user_articles %}
        {% for article in user_articles %}
            {% if article.is_visible %}
                <div class="row article-publication-item published">
            {% else %}
                <div class="row article-publication-item">
            {% endif %}
                <div class="large-1 columns">
                    <div class="date-box">
                        {% with date=article.pubdate %}
                            {% include "misc/datebox.part.html" %}
                        {% endwith %}
                    </div>
                </div>
                <div class="large-10 columns">
                    <a href="{{ article.get_absolute_url }}">{{ article.title }} </a>
                    {% if article.is_beta %}<span class="label alert">BETA</span>{% endif %}
                    <p>{{ article.description }}</p>
                </div>
                <div class="large-1 columns">
                    <a href="{{ article.get_edit_url }}">
                        <i class="icon-edit"></i>
                        Éditer
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="large-12 columns">
                Aucun article n'a été rédigé.
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="large-12 columns">
            <h3>Tutoriels</h3>
        </div>
    </div>

    {% if user_tutorials %}
        {% for tuto in user_tutorials %}
            {% if tuto.is_visible %}
                <div class="row article-publication-item published">
            {% else %}
                <div class="row article-publication-item">
            {% endif %}
                <div class="large-1 columns">
                    <div class="date-box">
                        {% with date=tuto.pubdate %}
                            {% include "misc/datebox.part.html" %}
                        {% endwith %}
                    </div>
                </div>
                <div class="large-10 columns">
                    <a href="{{ tuto.get_absolute_url }}">{{ tuto.title }} </a>
                    {% if tuto.is_beta %}<span class="label alert">BETA</span>{% endif %}
                    <p>{{ tuto.description }}</p>
                </div>
                <div class="large-1 columns">
                    <a href="{% url "pdp.tutorial.views.edit_tutorial" %}?tutoriel={{ tuto.pk }}">
                        <i class="icon-edit"></i>
                        Éditer
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="large-12 columns">
                Aucun tutoriel n'a été rédigé.
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/member/register.html
{% extends "member/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    S'incrire
{% endblock %}

{% block headline %}
    S'inscrire
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">S'inscrire</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
                {{ error }}
            {% endif %}
            <p>
                <strong>Vous êtes sur le point de vous inscrire sur Progdupeupl</strong> ; si vous
                possédez déjà un compte, merci de <a href="{% url "pdp.member.views.login_view" %}">vous connecter</a>
                à la place.
            </p>
            <p>
                Veuillez fournir les informations nécessaires dans le
                formulaire suivant afin de poursuivre votre inscription.
            </p>
            {% crispy form %}
        {% else %}
            <p>Vous êtes déjà connecté.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/member/register_success.html
{% extends "member/base.html" %}

{% block title %}
    Inscription réussie
{% endblock %}

{% block headline %}
    Inscription réussie
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Inscription</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Vous avez bien été inscrit au site. <a href="{% url "pdp.member.views.details" user.username %}">Voir votre profil</a>.
        </p>
    </div>
</div>

{% endblock %}

templates/member/settings_account.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url "pdp.member.views.settings_profile" %}">Paramètres</a></li>
    <li class="current"><a href="#">Compte</a></li>
{% endblock %}

{% block subnav %}
    <dd><a href="{% url "pdp.member.views.settings_profile" %}">Profil</a></dd>
    <dd class="active"><a href="{% url "pdp.member.views.settings_account" %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>
{% endblock %}

templates/member/settings_base.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
   Paramètres
{% endblock %}

{% block headline %}
   Paramètres
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <dl class="sub-nav">
                {% block subnav %}{% endblock %}
            </dl>
        </div>
    </div>
    {% block settings_form %}{% endblock %}
{% endblock %}

templates/member/settings_profile.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url "pdp.member.views.settings_profile" %}">Paramètres</a></li>
    <li class="current"><a href="#">Profil</a></li>
{% endblock %}

{% block subnav %}
    <dd class="active"><a href="{% url "pdp.member.views.settings_profile" %}">Profil</a></dd>
    <dd><a href="{% url "pdp.member.views.settings_account" %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
    <div class="row">
        <div class="large-12 columns">
            {% crispy form %}
        </div>
    </div>
{% endblock %}