pdp/gallery/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
     # Viewing a gallery
    url(r'^nouveau$', views.new_gallery),
    url(r'^modifier$', views.modify_gallery),
    url(r'^(?P<gal_pk>\d+)/(?P<gal_slug>.+)', views.gallery_details),
    url(r'^$', views.gallery_list),
    url(r'^image/ajouter/(?P<gal_pk>\d+)$', views.new_image),
    url(r'^image/modifier$', views.modify_image),
    url(r'^image/editer/(?P<gal_pk>\d+)/(?P<img_pk>\d+)$', views.edit_image),
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.models import User, Group

from haystack.views import SearchView
from haystack.forms import ModelSearchForm

from rest_framework import viewsets, routers

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    model = User

class GroupViewSet(viewsets.ModelViewSet):
    model = Group

# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = patterns('',
    url(r'^articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^messages/', include('pdp.messages.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('pdp.pages.urls')),
    url(r'^galerie/', include('pdp.gallery.urls')),
    url(r'^api/', include('pdp.api.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),

    url(r'^recherche/', SearchView(
            template='search/search.html',
            form_class=ModelSearchForm),
        name='haystack_search'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SERVE:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/gallery/models.py
# coding: utf-8

import os
import uuid
import string

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.urlresolvers import reverse


def image_path(instance, filename):
    '''Return path to an image'''
    ext = filename.split('.')[-1]
    filename = u'{}.{}'.format(str(uuid.uuid4()), string.lower(ext))
    return os.path.join('galleries', str(instance.gallery.pk), filename)


class UserGallery(models.Model):
    class Meta:
        verbose_name = "Galeries de l'utilisateur"
        verbose_name_plural = "Galeries de l'utilisateur"

    user = models.ForeignKey(User, verbose_name=('Membre'))
    gallery = models.ForeignKey('Gallery', verbose_name=('Galerie'))
    MODE_CHOICES = (
        ('R', 'Lecture'),
        ('W', 'Ecriture')
    )
    mode = models.CharField(max_length=1, choices=MODE_CHOICES, default='R')

    def __unicode__(self):
        '''Textual form of an User Gallery'''
        return u'Galerie "{0}" envoye par {1}'.format(self.gallery,
                                                      self.user)

    def is_write(self):
        return self.mode == 'W'

    def is_read(self):
        return self.mode == 'R'

    def get_images(self):
        return Image.objects.all()\
            .filter(gallery=self.gallery)\
            .order_by('update')

    def get_gallery(self, user):
        return Gallery.objects.all()\
            .filter(pk=self.gallery.pk)


class Image(models.Model):
    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

    gallery = models.ForeignKey('Gallery', verbose_name=('Galerie'))
    title = models.CharField('Titre', max_length=80)
    slug = models.SlugField(max_length=80)
    physical = models.ImageField(upload_to=image_path)
    legend = models.CharField('Légende', max_length=80)
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)
    update = models.DateTimeField(
        'Date de modification', null=True, blank=True)

    def __unicode__(self):
        '''Textual form of an Image'''
        return self.title

    def get_absolute_url(self):
        return '{0}/{1}'.format(settings.MEDIA_URL, self.physical)

    def get_extension(self):
        return os.path.splitext(self.nom_physique)[1]

# These two auto-delete files from filesystem when they are unneeded:


@receiver(models.signals.post_delete, sender=Image)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes image from filesystem
    when corresponding object is deleted.
    """
    if instance.physical:
        if os.path.isfile(instance.physical.path):
            os.remove(instance.physical.path)


class Gallery(models.Model):

    class Meta:
        verbose_name = "Galerie"
        verbose_name_plural = "Galeries"

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous titre', max_length=200, blank=True)
    slug = models.SlugField(max_length=80)
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)
    update = models.DateTimeField(
        'Date de modification', null=True, blank=True)

    def __unicode__(self):
        '''Textual form of an Gallery'''
        return self.title

    def get_absolute_url(self):
        return reverse('pdp.gallery.views.gallery_details',
                       args=[self.pk, self.slug])

    def get_users(self):
        return UserGallery.objects.all()\
            .filter(gallery=self)

    def get_images(self):
        return Image.objects.all()\
            .filter(gallery=self)\
            .order_by('pubdate')

    def get_last_image(self):
        return Image.objects.all()\
            .filter(gallery=self)\
            .order_by('-pubdate')[0]

pdp/gallery/forms.py
from django import forms
from django.conf import settings


class UserGalleryForm(forms.Form):
    user= forms.CharField('Membre', required=False)
    gallery = forms.CharField('Gallery', required=False)
    mode = forms.CharField('Mode', required=False)
    
class GalleryForm(forms.Form):
    title= forms.CharField(max_length=80)
    subtitle = forms.CharField(max_length=200, required=False)

class ImageForm(forms.Form):
    gallery = forms.CharField('Gallery', required=False)
    physical = forms.ImageField(
        label='Select an image',
        help_text='max. '+str(settings.IMAGE_MAX_SIZE)+' megabytes'
    , required=False)
    title = forms.CharField('Titre')
    legend = forms.CharField('Legende', required=False)

pdp/gallery/views.py
# coding: utf-8

# The max size in bytes

from django.conf import settings
from datetime import datetime

from django.shortcuts import redirect, get_object_or_404
from django.http import Http404

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse

from pdp.utils import render_template, slugify
from pdp.gallery.models import UserGallery, Image, Gallery
from pdp.gallery.forms import ImageForm, GalleryForm, UserGalleryForm


@login_required
def gallery_list(request):
    '''
    Display the gallery list with all their images
    '''
    galleries = UserGallery.objects.all().filter(user=request.user)

    return render_template('gallery/gallery_list.html', {
        'galleries': galleries
    })


@login_required
def gallery_details(request, gal_pk, gal_slug):
    '''
    Gallery details
    '''

    gal = get_object_or_404(Gallery, pk=gal_pk)
    gal_mode = get_object_or_404(UserGallery, gallery=gal, user=request.user)
    images = gal.get_images()

    return render_template('gallery/gallery_details.html', {
        'gallery': gal,
        'gallery_mode': gal_mode,
        'images': images
    })


@login_required
def new_gallery(request):
    '''
    Creates a new gallery
    '''
    if request.method == 'POST':
        form = GalleryForm(request.POST)
        if form.is_valid():
            data = form.data
            # Creating the gallery
            gal = Gallery()
            gal.title = data['title']
            gal.subtitle = data['subtitle']
            gal.slug = slugify(data['title'])
            gal.pubdate = datetime.now()
            gal.save()

            # Attach user
            userg = UserGallery()
            userg.gallery = gal
            userg.mode = 'W'
            userg.user = request.user
            userg.save()

            return redirect(gal.get_absolute_url())

        else:
            # TODO: add errors to the form and return it
            raise Http404
    else:
        form = GalleryForm()
        return render_template('gallery/new_gallery.html', {
            'form': form
        })


@login_required
def modify_gallery(request):
    '''Modify gallery instance'''

    if request.method != 'POST':
        raise Http404

    # Global actions

    if 'delete_multi' in request.POST:
        l = request.POST.getlist('items')

        perms = UserGallery.objects\
                .filter(gallery__pk__in=l, user=request.user, mode='W')\
                .count()

        # Check that the user has the RW right on each gallery
        if perms < len(l):
            raise Http404

        # Delete all the permissions on all the selected galleries
        UserGallery.objects.filter(gallery__pk__in=l).delete()
        # Delete all the images of the gallery (autodelete of file)
        Image.objects.filter(gallery__pk__in=l).delete()
        # Finally delete the selected galleries
        Gallery.objects.filter(pk__in=l).delete()

        return redirect(reverse('pdp.gallery.views.gallery_list'))

    # Gallery-specific actions

    try:
        gal_pk = request.POST['gallery']
    except KeyError:
        raise Http404

    gal = get_object_or_404(Gallery, pk=gal_pk)
    gal_mode = get_object_or_404(UserGallery, gallery=gal, user=request.user)

    # Disallow actions to read-only members
    if gal_mode.mode != 'W':
        raise Http404

    if 'adduser' in request.POST:
        form = UserGalleryForm(request.POST)
        u = get_object_or_404(User, username=request.POST['user'])
        if form.is_valid():
            ug = UserGallery()
            ug.user = u
            ug.gallery = gal
            ug.mode = 'W'
            ug.save()


    return redirect(gal.get_absolute_url())


@login_required
def del_image(request, gal_pk):
    gal = get_object_or_404(Gallery, pk=gal_pk)
    if request.method == 'POST':
        liste = request.POST.getlist('items')
        Image.objects.filter(pk__in=liste).delete()
        return redirect(gal.get_absolute_url())
    return redirect(gal.get_absolute_url())


@login_required
def edit_image(request, gal_pk, img_pk):
    '''
    Creates a new image
    '''
    gal = get_object_or_404(Gallery, pk=gal_pk)
    img = get_object_or_404(Image, pk=img_pk)

    if request.method == 'POST':
        form = ImageForm(request.POST)
        if form.is_valid():
            img.title = request.POST['title']
            img.legend = request.POST['legend']
            img.update = datetime.now()

            img.save()

            # Redirect to the document list after POST
            return redirect(gal.get_absolute_url())
        else:
            # TODO: add errors to the form and return it
            raise Http404
    else:
        form = ImageForm()  # A empty, unbound form
        return render_template('gallery/edit_image.html', {
            'form': form,
            'gallery': gal,
            'image': img
        })


@login_required
def modify_image(request):
    # We only handle secured POST actions
    if request.method != 'POST':
        raise Http404

    try:
        gal_pk = request.POST['gallery']
    except KeyError:
        raise Http404

    gal = get_object_or_404(Gallery, pk=gal_pk)
    gal_mode = get_object_or_404(UserGallery, gallery=gal, user=request.user)

    # Only allow RW users to modify images
    if gal_mode.mode != 'W':
        raise Http404

    if 'delete' in request.POST:
        img = get_object_or_404(Image, pk=request.POST['image'])
        img.delete()

    elif 'delete_multi' in request.POST:
        l = request.POST.getlist('items')
        Image.objects.filter(pk__in=l).delete()

    return redirect(gal.get_absolute_url())


@login_required
def new_image(request, gal_pk):
    '''
    Creates a new image
    '''
    gal = get_object_or_404(Gallery, pk=gal_pk)

    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid() \
           and request.FILES['physical'].size < settings.IMAGE_MAX_SIZE:
            img = Image()
            img.physical = request.FILES['physical']
            img.gallery = gal
            img.title = request.POST['title']
            img.slug = slugify(request.FILES['physical'])
            img.legend = request.POST['legend']
            img.pubdate = datetime.now()

            img.save()

            # Redirect to the document list after POST
            return redirect(gal.get_absolute_url())
        else:
            # TODO: add errors to the form and return it
            raise Http404
    else:
        form = ImageForm()  # A empty, unbound form
        return render_template('gallery/new_image.html', {
            'form': form,
            'gallery': gal
        })

templates/gallery/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Galeries
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "pdp.gallery.views.gallery_list" %}">Galeries</a></li>
{% endblock %}

templates/gallery/edit_image.html
{% extends "gallery/base.html" %}

{% block title %}
    Éditer une image
{% endblock %}

{% block headline %}
    Éditer une image
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></li>
    <li class="current"><a href="javascript:;">Éditer une Image</a></li>
{% endblock %}

{% block content %}
	<div class="row">
    <div class="large-12 columns">
        <div class="large-6 columns">
            <img src="{{ image.physical.url }}" alt="" />
        </div>
        <div class="large-6 columns">
            <form action="{% url "pdp.gallery.views.edit_image" gallery.pk image.pk %}" method="POST">
                <input type="text" placeholder="Titre" name="title" value="{{ image.title }}" /><br />
                <input type="text" placeholder="Légende" name="legend" value="{{ image.legend }}" /><br />

                <div style="text-align: center;">
                    <button type="submit" class="button">
                        <i class="icon-plus icon-white"></i>
                        Éditer
                    </button>

                    <a href="{{ gallery.get_absolute_url }}" class="button secondary">
                        Retour
                    </a>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/gallery/gallery_details.html
{% extends "gallery/base.html" %}
{% load profile %}

{% block title %}
    {{ gallery.title }}
{% endblock %}

{% block headline %}
    {{ gallery.title }}
{% endblock %}

{% block headline-sub %}
    {{ gallery.subtitle }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">{{ gallery.title }}</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <p>
            Membres partageant cette galerie :
            {% for u in gallery.get_users %}
                {% with member=u.user %}
                    {% include "member/member_item_common.part.html" %}
                    (<i class="fi-{{ u.mode|mode }} size-18"></i>)
                {% endwith %}
            {% endfor %}
        </p>
        {% if gallery_mode.is_write %}
        <form action="{% url "pdp.gallery.views.modify_gallery" %}"
            method="post">
            <input type="text" name="user" placeholder="Nom de l'utilisateur">
            <input type="hidden" name="gallery" value={{ gallery.pk }}>
            <button name="adduser" class="button secondary">
                Ajouter un membre
            </button>
            {% csrf_token %}
        </form>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <form id="form" name="form" method="POST" action="{% url "pdp.gallery.views.modify_image" %}">
            <input type="hidden" name="gallery" value="{{ gallery.pk }}">
            <div class="row">
                <div class="large-8 columns">   
                    <h3>Images</h3>
                </div>
                <div class="large-4 columns">
                    <div class="right">
                        <a href="{% url "pdp.gallery.views.new_image" gallery.pk %}" class="button">
                            Ajouter une image
                        </a>
                        <button name="delete_multi" class="button secondary">
                            Supprimer
                        </button>
                    </div>
                </div>
            </div>
            <table>
                <thead>
                   <tr>
                       <th style="width: 3%;"></th>
                       <th style="width: 180px;">Image</th>
                       <th style="width: 72%;">Titre</th>
                   </tr>
                </thead>
                <tbody>
                    {% for img in gallery.get_images %}
                        <tr>
                            <td>
                                <input name="items" type="checkbox" value="{{ img.pk }}" />
                            </td>
                            <td>
                                <div>
                                    <a href="{% url "pdp.gallery.views.edit_image" gallery.pk img.pk %}">
                                        <img src="{{ img.physical.url }}" style="max-width:180px ;max-height:180px" data-caption="{{ img.title }}"
                                             alt="{{ img.title }}" />
                                    </a>
                                </div>
                            </td>
                            <td>
                                <a href="{% url "pdp.gallery.views.edit_image" gallery.pk img.pk %}">{{ img.title }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% csrf_token %}
        </form>
    </div>
</div>


{% endblock %}

templates/gallery/gallery_list.html
{% extends "gallery/base.html" %}

{% block title %}
    Index
{% endblock %}

{% block headline %}
    Galeries
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}
<form id="form" name="form" method="POST" action="{% url "pdp.gallery.views.modify_gallery" %}">
<div class="row">
    <div class="small-12 columns">
        <div class="small-3 columns">
            <a href="{% url "pdp.gallery.views.new_gallery" %}" class="button">Nouvelle galerie</a>
        </div>
        <div class="small-2 columns">
            <button type="submit" name="delete_multi" class="button secondary">
                Supprimer
            </button>
        </div>
    </div>
</div>
<div class="row">
    <div class="small-12 columns">
        {% for gallery in galleries %}
            <div class="small-6 columns expand">
                <div class="panel">
                    <div class="row">
                        <div class="small-8 columns">
                            <h3><a href="{{ gallery.gallery.get_absolute_url }}">{{ gallery.gallery.title }} ({{ gallery.gallery.get_images.count }})</a></h3>
                        </div>
                        <div class="small-1 columns">
                            <p>
                            {% if gallery.is_write %}
                                <input name="items" type="checkbox" value="{{ gallery.gallery.pk }}" />
                            {% endif %}
                            </p>
                        </div>
                    </div>
                    <p>
                        {{ gallery.gallery.subtitle }}
                    </p>
                    <ul class="clearing-thumbs clearing-feature" data-clearing>
                        {% for img in gallery.gallery.get_images %}
                            {% if gallery.gallery.get_last_image.pk == img.pk %}
                                <li class="clearing-featured-img fix-height visible">
                            {% else %}
                                <li class="fix-height">
                            {% endif %}
                                    <a href="{{ img.physical.url }}">
                                        <img alt="" src="{{ img.physical.url }}" style="max-width:180px ;max-height:180px" data-caption="{{ img.legend }}" />
                                    </a>
                                </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% csrf_token %}
</form>
{% endblock %}

templates/gallery/new_gallery.html
{% extends "gallery/base.html" %}

{% block title %}
    Nouvelle galerie
{% endblock %}

{% block headline %}
    Nouvelle galerie
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">Nouvelle galerie</a></li>
{% endblock %}

{% block content %}
	<div class="row">
    <div class="large-12 columns">
        <form action="{% url "pdp.gallery.views.new_gallery" %}" method="POST">
            <input type="text" placeholder="Titre" name="title" />
            <br />
            <input type="text" placeholder="Sous-titre" name="subtitle">
            <br />

            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-plus icon-white"></i>
                    Créer
                </button>

                <a href="{% url "pdp.gallery.views.gallery_list" %}" class="button secondary">
                    Retour
                </a>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

{% endblock %}

templates/gallery/new_image.html
{% extends "gallery/base.html" %}

{% block title %}
    Nouvelle image
{% endblock %}

{% block headline %}
    Nouvelle image
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></li>
    <li class="current"><a href="javascript:;">Nouvelle image</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="{% url "pdp.gallery.views.new_image" gallery.pk %}" method="POST" enctype="multipart/form-data">
            <input type="file" id="id_physical" name="physical" onchange="load_field()"/><br />
            <input type="text" id="id_titre" placeholder="Titre" name="title" /><br />
            <input type="text" placeholder="Légende" name="legend" /><br />

            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-plus icon-white"></i>
                    Créer
                </button>

                <a href="{{ gallery.get_absolute_url }}" class="button secondary">
                    Retour
                </a>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

{% endblock %}
{% block additionnal-js %}
    <script>
        function load_field() {
            var ph=document.getElementById("id_physical");
            var tab=ph.value.split('\\');
            var lib=tab[tab.length-1];

            if($('#id_titre').val() == '') {
                $('#id_titre').val(lib);
            }
        }
    </script>
{% endblock %}

templates/gallery/share_gallery.html
{% extends "gallery/base.html" %}

{% block title %}
    Partager une galerie
{% endblock %}

{% block headline %}
    Partager : {{ gallery.title }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">Partager une galerie</a></li>
{% endblock %}

{% block content %}
	<div class="row">
    <div class="large-6 columns large-centered">
        <form action='{% url "pdp.gallery.views.share_gallery" gallery.pk %}' method="POST">
            
            <label for="mode">Mode d'accès</label>
            <select id="mode" name="mode" class="large">
                <option value="R">Lecture seule</option>
                <option value="W">Lecture/écriture</option>
            </select>
            <input type="text" placeholder="Membre" name="user" class="input-xxlarge" value="" /><br />
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="fi-share size-18"></i>
                    Partager
                </button>
                <a href="{% url "pdp.gallery.views.gallery_list" %}" class="button secondary">
                    Retour
                </a>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

{% endblock %}